dist: xenial
language: python
python:
- "2.7"
- "3.6"
- "3.7"
- "3.8"
- "3.9"
install:
  - pip install -r requirements-test.txt
script:
- pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: domain-connect
  password:
    secure: 2ddCq65Cny17sogIFblscpidIhFYtS43ibRY4UkQu+H3ZRY8FCR7fX8Eeq8oCq2bI2Qsg5QEm9u09mZjH217YOi/uUPuDKU/bIur6lxRAHYsh5nnoqCQXVkDZ/5aQKysucxQFzQHvv47ARZZEwKeOCM9OsKbFYHgjTtfl23JE6hsLFdxRx6nT6uC1fxFJ+dxjWZoUIKIe2ymTy0sqed/gqs40sGa3nHc6qvQALQTKz+4lBEQJ74x47l58dLbDl4yi9aEv5pGxVpfmjrRVbSUSjj/j8h59ocXRzc0ATqItLdtQbt59SU7JYAcWnwCNj8b4jUP+oZVAqSnBENR+CyOHg+0s/PcuIWUdFAj1fNgqJs3tvwBZSnc4N60nQNSKfsJJ4pKK+jT1Z2A/gyGN0Fu7tTpYm0bgwAIO7JFheFVO4ykrjbP3+zQrP9TR/hlECIodZvzfw7zspmNPSkw0lNVzY0YHbtilHqqLk1A+uKTc3XDT8yrTQEsp/gfMwwZ/HJY+zFzy94ygyZT22ggB9o3kEsKvkerWK1Jhvyjk9CPl2Rs0jXKAzlWAjTnyZypwx5XrURYYqnxekWv5BSNg2Q6Bgt9lZmsfDxGjmUVD8t/CreXimAP2KzOxN/hJ1tDsvGTns3YGzh331yMQtFACboHxEU8Bc3sl8CScKmU2rJPCz4=
  on:
    tags: true

