name: Python package

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - python-version: 2.7
            os: ubuntu-20.04
          - python-version: 3.6
            os: ubuntu-20.04
          - python-version: 3.7
            os: ubuntu-22.04
          - python-version: 3.8
            os: ubuntu-22.04
          - python-version: 3.9
            os: ubuntu-22.04
          - python-version: "3.10"
            os: ubuntu-22.04
          - python-version: "3.11"
            os: ubuntu-22.04
          - python-version: "3.12"
            os: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} != 2.7
      if: ${{ matrix.python-version != '2.7' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Python 2.7
      if: ${{ matrix.python-version == '2.7' }}
      run: | 
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        sudo python get-pip.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt

    - name: Test with pytest
      run: |
        pytest

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: build distribution packages
      run: python setup.py sdist bdist_wheel
    - name: Build and publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: domain-connect
        password: ${{ secrets.PYPI_PASSWORD }}
        skip_existing: true

